import { useState, useEffect } from 'react';
import { Eye, Code, Download, Plus, Save, Upload, Play, Database, Trash2, Undo, Redo, X, Table2 } from 'lucide-react';
import { useAppStore } from '../stores/appStore';
import AddTableModal from './AddTableModal';
import DataBrowser from './DataBrowser';

export default function Toolbar() {
  const { viewMode, setViewMode, tables, setTables, isConnected, setSuccess, setError, connectionId, setConnectionModal, setConnection, connectionConfig, currentDatabase, undoStack, redoStack, undo, redo, clearHistory, selectedTable } = useAppStore();
  const [showAddTableModal, setShowAddTableModal] = useState(false);
  const [showSQLPreviewModal, setShowSQLPreviewModal] = useState(false);
  const [generatedSQL, setGeneratedSQL] = useState('');
  const [showDataPanel, setShowDataPanel] = useState(false);
  const [showQueryRunner, setShowQueryRunner] = useState(false);

  // Keyboard shortcuts for undo/redo
  useEffect(() => {
    const handleKeyDown = (e) => {
      // Cmd+Z (Mac) or Ctrl+Z (Windows) - Undo
      if ((e.metaKey || e.ctrlKey) && e.key === 'z' && !e.shiftKey) {
        e.preventDefault();
        undo();
      }
      // Cmd+Shift+Z (Mac) or Ctrl+Y (Windows) - Redo
      if (((e.metaKey || e.ctrlKey) && e.shiftKey && e.key === 'z') || ((e.ctrlKey) && e.key === 'y')) {
        e.preventDefault();
        redo();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [undo, redo]);

  const handleExportSQL = async () => {
    try {
      const sql = generateSQL();
      setGeneratedSQL(sql);
      setShowSQLPreviewModal(true);
    } catch (error) {
      console.error('Generate SQL error:', error);
      setError('Failed to generate SQL: ' + error.message);
    }
  };

  const handleDownloadSQL = () => {
    const blob = new Blob([generatedSQL], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `schema_${Date.now()}.sql`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setSuccess('SQL file downloaded');
  };

  const generateSQL = () => {
    const tablesData = tables.map(table => ({
      name: table.name,
      columns: table.columns.map(col => ({
        name: col.name || col.Field,
        type: col.type || col.Type,
        length: col.length,
        notNull: col.notNull || col.Null === 'NO',
        primaryKey: col.primaryKey || col.Key === 'PRI',
        autoIncrement: col.autoIncrement || col.Extra?.includes('auto_increment'),
        unique: col.unique,
        default: col.default || col.Default
      })),
      foreignKeys: table.foreignKeys || []
    }));

    // Generate SQL
    let sql = '-- Generated by zxwdb\n';
    sql += `-- Date: ${new Date().toISOString()}\n\n`;

    tablesData.forEach(table => {
      sql += `CREATE TABLE \`${table.name}\` (\n`;

      const columnDefs = table.columns.map(col => {
        let def = `  \`${col.name}\` ${col.type}`;
        if (col.length) def += `(${col.length})`;
        if (col.notNull) def += ' NOT NULL';
        if (col.autoIncrement) def += ' AUTO_INCREMENT';
        if (col.unique) def += ' UNIQUE';
        if (col.default !== undefined && col.default !== null) {
          def += ` DEFAULT ${col.default}`;
        }
        return def;
      });

      sql += columnDefs.join(',\n');

      // Add primary key
      const primaryKeys = table.columns.filter(col => col.primaryKey);
      if (primaryKeys.length > 0) {
        const pkNames = primaryKeys.map(col => `\`${col.name}\``).join(', ');
        sql += `,\n  PRIMARY KEY (${pkNames})`;
      }

      sql += '\n);\n\n';
    });

    return sql;
  };

  const handleBackToDatabases = () => {
    // Clear current database but keep connection
    const newConfig = { ...connectionConfig };
    delete newConfig.database;
    setConnection(null, newConfig);
    setTables([]);
  };

  const handleAutoArrange = () => {
    // Auto-arrange tables in a clean grid
    const gridCols = 3;
    const horizontalSpacing = 400;
    const verticalSpacing = 350;
    const startX = 150;
    const startY = 100;

    const arrangedTables = tables.map((table, index) => ({
      ...table,
      position: {
        x: startX + (index % gridCols) * horizontalSpacing,
        y: startY + Math.floor(index / gridCols) * verticalSpacing
      }
    }));

    setTables(arrangedTables);
    setSuccess('Tables auto-arranged in grid layout');
  };

  const handleClearCache = () => {
    if (confirm('Clear all cached data (tables and relationships)? You will be redirected to database selection.')) {
      localStorage.removeItem('zxwdb_relationships');
      localStorage.removeItem('zxwdb_tables');
      localStorage.removeItem('zxwdb_currentDatabase');
      setTables([]);
      clearHistory(); // Clear undo/redo history
      
      // Clear database from connection config to trigger redirect to database selection
      if (connectionConfig) {
        const newConfig = { ...connectionConfig };
        delete newConfig.database;
        setConnection(connectionId, newConfig);
      }
      
      setSuccess('Cache cleared! Select a database to continue.');
    }
  };

  const handleFlowchartLayout = () => {
    // Toggle flowchart mode
    const newMode = !flowchartMode;
    setFlowchartMode(newMode);

    if (newMode) {
      // Enable flowchart mode and arrange hierarchically
      const { relationships: rels } = useAppStore.getState();

    // Analyze relationships to determine hierarchy
    const childTables = new Set();
    const parentTables = new Set();

    rels.forEach(rel => {
      parentTables.add(rel.source);
      childTables.add(rel.target);
    });

    // Root tables: have no incoming relationships (are never targets)
    const rootTables = tables.filter(t => !childTables.has(t.name) || !parentTables.has(t.name));

    // Get tables by level
    const tablesByLevel = new Map();
    const processedTables = new Set();

    // Level 0: Root tables (no parents or pure parents)
    const level0 = tables.filter(t => {
      const isTarget = rels.some(rel => rel.target === t.name);
      return !isTarget; // Tables that are never targets = root tables
    });

    if (level0.length > 0) {
      tablesByLevel.set(0, level0);
      level0.forEach(t => processedTables.add(t.name));
    }

    // Build remaining levels based on dependencies
    let currentLevel = 1;
    let remainingTables = tables.filter(t => !processedTables.has(t.name));

    while (remainingTables.length > 0 && currentLevel < 10) {
      const currentLevelTables = remainingTables.filter(table => {
        // A table can be in current level if all its parents are already processed
        const parentRels = rels.filter(rel => rel.target === table.name);
        return parentRels.every(rel => processedTables.has(rel.source));
      });

      if (currentLevelTables.length === 0) {
        // No more tables can be placed, put remaining in current level
        tablesByLevel.set(currentLevel, remainingTables);
        remainingTables.forEach(t => processedTables.add(t.name));
        break;
      }

      tablesByLevel.set(currentLevel, currentLevelTables);
      currentLevelTables.forEach(t => processedTables.add(t.name));
      remainingTables = tables.filter(t => !processedTables.has(t.name));
      currentLevel++;
    }

    // Position tables in flowchart layout
    const horizontalSpacing = 350;
    const verticalSpacing = 300;
    const startX = 150;
    const startY = 80;

    const arrangedTables = [];

    tablesByLevel.forEach((levelTables, level) => {
      const levelWidth = (levelTables.length - 1) * horizontalSpacing;
      const levelStartX = startX + (levelWidth / 2) - (levelWidth / 2);

      levelTables.forEach((table, indexInLevel) => {
        arrangedTables.push({
          ...table,
          position: {
            x: levelStartX + indexInLevel * horizontalSpacing,
            y: startY + level * verticalSpacing
          }
        });
      });
    });

    setTables(arrangedTables);
    setSuccess('Flowchart mode enabled - Tables arranged in hierarchy');
    } else {
      // Disable flowchart mode - just show success message
      setSuccess('Flowchart mode disabled - Showing regular table view');
    }
  };

  const handleExportProject = () => {
    try {
      const project = {
        name: 'zxwdb-project',
        version: '1.0.0',
        createdAt: new Date().toISOString(),
        tables,
        viewMode
      };

      const json = JSON.stringify(project, null, 2);
      const blob = new Blob([json], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `zxwdb_project_${Date.now()}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      setSuccess('Project saved successfully');
    } catch (error) {
      console.error('Save project error:', error);
      setError('Failed to save project: ' + error.message);
    }
  };

  const handleLoadProject = () => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.json';
    input.onchange = (e) => {
      const file = e.target.files[0];
      if (file) {
        const reader = new FileReader();
        reader.onload = (event) => {
          try {
            const project = JSON.parse(event.target.result);
            if (project.tables) {
              setTables(project.tables);
              if (project.viewMode) {
                setViewMode(project.viewMode);
              }
              setSuccess('Project loaded successfully!');
            } else {
              setError('Invalid project file');
            }
          } catch (error) {
            console.error('Load project error:', error);
            setError('Failed to load project: ' + error.message);
          }
        };
        reader.readAsText(file);
      }
    };
    input.click();
  };

  return (
    <div className="bg-[#2d2d2d] border-b border-[#3a3a3a] px-4 py-2 flex items-center justify-between">
      <div className="flex items-center gap-2">
        {/* View Mode Toggle */}
        <div className="flex bg-[#1e1e1e] rounded p-1 border border-[#3a3a3a]">
          <button
            onClick={() => setViewMode('ERD')}
            className={`px-3 py-1.5 rounded text-xs font-medium font-mono transition-colors ${
              viewMode === 'ERD'
                ? 'bg-[#4ec9b0] text-[#1e1e1e]'
                : 'text-[#808080] hover:text-[#d4d4d4]'
            }`}
          >
            <Eye className="w-3 h-3 inline mr-1" />
            ERD
          </button>
          <button
            onClick={() => setViewMode('LRS')}
            className={`px-3 py-1.5 rounded text-xs font-medium font-mono transition-colors ${
              viewMode === 'LRS'
                ? 'bg-[#4ec9b0] text-[#1e1e1e]'
                : 'text-[#808080] hover:text-[#d4d4d4]'
            }`}
          >
            <Code className="w-3 h-3 inline mr-1" />
            LRS
          </button>
        </div>

        <div className="h-6 w-px bg-[#3a3a3a] mx-2"></div>

        {isConnected && (connectionConfig?.database || currentDatabase) ? (
          <>
            {/* Database Info Display */}
            <div className="px-3 py-1.5 text-xs font-mono text-[#4ec9b0] bg-[#1e1e1e] rounded border border-[#3a3a3a] flex items-center gap-2">
              <Database className="w-3 h-3" />
              <span className="font-semibold">{currentDatabase || connectionConfig?.database}</span>
              <span className="text-[#808080]">@{connectionConfig?.host || 'localhost'}</span>
            </div>
            
            <button
              onClick={handleBackToDatabases}
              className="px-3 py-1.5 text-xs font-medium font-mono text-[#569cd6] hover:bg-[#1e1e1e] rounded flex items-center gap-1 border border-transparent hover:border-[#3a3a3a] transition-colors"
            >
              <Database className="w-3 h-3" />
              Switch Database
            </button>
            <button
              onClick={() => setConnectionModal(true)}
              className="px-3 py-1.5 text-xs font-medium font-mono text-[#dcdcaa] hover:bg-[#1e1e1e] rounded flex items-center gap-1 border border-[#dcdcaa] hover:border-[#dcdcaa] transition-colors"
            >
              Change Connection
            </button>
          </>
        ) : isConnected ? (
          <button
            onClick={() => setConnectionModal(true)}
            className="px-3 py-1.5 text-xs font-medium font-mono text-[#dcdcaa] hover:bg-[#1e1e1e] rounded flex items-center gap-1 border border-[#dcdcaa] hover:border-[#dcdcaa] transition-colors"
          >
            Change Connection
          </button>
        ) : (
          <button
            onClick={() => setConnectionModal(true)}
            className="px-3 py-1.5 text-xs font-medium font-mono text-[#1e1e1e] bg-[#4ec9b0] hover:bg-[#569cd6] rounded flex items-center gap-1 transition-colors"
          >
            Connect to Database
          </button>
        )}

        <div className="h-6 w-px bg-[#3a3a3a] mx-2"></div>

        {/* Add Table Button */}
        <button
          onClick={() => setShowAddTableModal(true)}
          className="px-3 py-1.5 text-xs font-medium font-mono text-[#d4d4d4] hover:bg-[#1e1e1e] rounded flex items-center gap-1 border border-transparent hover:border-[#3a3a3a] transition-colors"
        >
          <Plus className="w-3 h-3" />
          Add Table
        </button>

        <div className="h-6 w-px bg-[#3a3a3a] mx-2"></div>

        {/* Undo Button */}
        <button
          onClick={undo}
          disabled={undoStack.length === 0}
          className="px-3 py-1.5 text-xs font-medium font-mono text-[#d4d4d4] hover:bg-[#1e1e1e] rounded flex items-center gap-1 border border-transparent hover:border-[#3a3a3a] transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
          title="Undo (Cmd+Z / Ctrl+Z)"
        >
          <Undo className="w-3 h-3" />
          Undo
        </button>

        {/* Redo Button */}
        <button
          onClick={redo}
          disabled={redoStack.length === 0}
          className="px-3 py-1.5 text-xs font-medium font-mono text-[#d4d4d4] hover:bg-[#1e1e1e] rounded flex items-center gap-1 border border-transparent hover:border-[#3a3a3a] transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
          title="Redo (Cmd+Shift+Z / Ctrl+Y)"
        >
          <Redo className="w-3 h-3" />
          Redo
        </button>

        <div className="h-6 w-px bg-[#3a3a3a] mx-2"></div>

        {/* Clear Cache Button */}
        <button
          onClick={handleClearCache}
          className="px-3 py-1.5 text-xs font-medium font-mono text-[#f48771] hover:bg-[#f48771] hover:text-[#1e1e1e] rounded flex items-center gap-1 border border-transparent hover:border-[#f48771] transition-colors"
          title="Clear cached tables and relationships"
        >
          <Trash2 className="w-3 h-3" />
          Clear Cache
        </button>
      </div>

      <div className="flex items-center gap-2">
        <span className="text-xs text-[#808080] font-mono">
          {tables.length} {tables.length === 1 ? 'table' : 'tables'}
        </span>

        <div className="h-6 w-px bg-[#3a3a3a] mx-2"></div>

        {/* Action Buttons */}
        <button
          onClick={handleLoadProject}
          className="px-3 py-1.5 text-xs font-medium font-mono text-[#d4d4d4] hover:bg-[#1e1e1e] rounded flex items-center gap-1 border border-transparent hover:border-[#3a3a3a] transition-colors"
        >
          <Upload className="w-3 h-3" />
          Load Project
        </button>

        <button
          onClick={handleExportProject}
          disabled={tables.length === 0}
          className="px-3 py-1.5 text-xs font-medium font-mono text-[#d4d4d4] hover:bg-[#1e1e1e] rounded flex items-center gap-1 border border-transparent hover:border-[#3a3a3a] transition-colors disabled:opacity-50"
        >
          <Download className="w-3 h-3" />
          Export Project
        </button>

        <button
          onClick={handleExportSQL}
          disabled={tables.length === 0}
          className="px-3 py-1.5 text-xs font-medium font-mono text-[#1e1e1e] bg-[#569cd6] hover:bg-[#4ec9b0] rounded flex items-center gap-1 transition-colors disabled:opacity-50"
        >
          <Code className="w-3 h-3" />
          Preview SQL
        </button>

        <button
          onClick={() => setShowDataPanel(true)}
          disabled={!connectionId}
          className="px-3 py-1.5 text-xs font-medium font-mono text-[#1e1e1e] bg-[#4ec9b0] hover:bg-[#5ed9c0] rounded flex items-center gap-1 transition-colors disabled:opacity-50"
          title="Browse table data"
        >
          <Database className="w-3 h-3" />
          Browse Data
        </button>
      </div>

      {/* Add Table Modal */}
      {showAddTableModal && (
        <AddTableModal onClose={() => setShowAddTableModal(false)} />
      )}

      {/* Data Browser */}
      {showDataPanel && connectionId && (
        <DataBrowser
          tables={tables}
          connectionId={connectionId}
          selectedTable={selectedTable}
          onClose={() => setShowDataPanel(false)}
        />
      )}

      {/* Execute SQL Modal */}
      {/* SQL Preview Modal */}
      {showSQLPreviewModal && (
        <div className="fixed inset-0 bg-black bg-opacity-70 flex items-center justify-center z-50">
          <div className="bg-[#2d2d2d] rounded border border-[#3a3a3a] shadow-xl w-full max-w-4xl max-h-[90vh] flex flex-col">
            {/* Header */}
            <div className="flex items-center justify-between p-4 border-b border-[#3a3a3a]">
              <h2 className="text-sm font-semibold text-[#d4d4d4] font-mono">SQL Preview</h2>
              <button onClick={() => setShowSQLPreviewModal(false)} className="text-[#808080] hover:text-[#d4d4d4]">
                <X className="w-5 h-5" />
              </button>
            </div>
            
            {/* SQL Content */}
            <div className="flex-1 overflow-y-auto p-4">
              <pre className="bg-[#1e1e1e] p-4 rounded border border-[#3a3a3a] text-xs font-mono text-[#d4d4d4] whitespace-pre-wrap">
                {generatedSQL}
              </pre>
            </div>
            
            {/* Footer */}
            <div className="flex gap-2 p-4 border-t border-[#3a3a3a]">
              <button
                onClick={() => {
                  navigator.clipboard.writeText(generatedSQL);
                  setSuccess('SQL copied to clipboard');
                }}
                className="px-4 py-2 border border-[#3a3a3a] rounded hover:bg-[#1e1e1e] text-xs font-mono text-[#d4d4d4] flex items-center gap-2"
              >
                <Code className="w-4 h-4" />
                Copy to Clipboard
              </button>
              <button
                onClick={handleDownloadSQL}
                className="flex-1 px-4 py-2 bg-[#4ec9b0] text-[#1e1e1e] rounded hover:bg-[#569cd6] text-xs font-medium flex items-center justify-center gap-2"
              >
                <Download className="w-4 h-4" />
                Download SQL File
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
